### ISSUE TITLE
Is there a way to update the phosphositeplus dataframe containing substrate/kinase binding sites?

### ISSUE THREAD

**Issue by sscho** [saezlab/kinact#1]
I noticed it's been 2 years since last updated. Is there a way we can update it?

Thanks,

Shawn

**Comment by jakob-wirbel** [comment]
Hey Shawn,

if you have installed the `pypath` package (see [here](https://github.com/saezlab/pypath)), then you can use the function  `__update_pypath_resource()` in kinact, which loads the kinase/substrate information from the latest version of `pypath`. 

Did this answer your question? 😃 

Cheers,
Jakob

**Comment by npalacioescat** [comment]
Inactive for >2 years. Considering the question is already answered, closing.
